version: "3"
services:
  oxigraph:
    image: ghcr.io/oxigraph/oxigraph:latest
    platform: linux/amd64
    ## To build from local source code:
    # build:
    #   context: .
    #   dockerfile: server/Dockerfile
    ports:
      - "7878:7878"
    volumes:
      - ./data:/data